# Generated by Django 5.0.4 on 2024-04-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
    ]
